-- Issue #106: planning backbone.  This is intentionally non-production until
-- a separately approved migration/deploy is performed.
CREATE TABLE IF NOT EXISTS timeline_templates (id TEXT PRIMARY KEY, name TEXT NOT NULL, description TEXT, active INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL, created_by_user_id TEXT REFERENCES users(id) ON DELETE SET NULL);
CREATE TABLE IF NOT EXISTS timeline_template_versions (id TEXT PRIMARY KEY, template_id TEXT NOT NULL REFERENCES timeline_templates(id) ON DELETE CASCADE, version_number INTEGER NOT NULL, name TEXT NOT NULL, snapshot_json TEXT NOT NULL, instantiated_at TEXT, created_at TEXT NOT NULL, created_by_user_id TEXT REFERENCES users(id) ON DELETE SET NULL, UNIQUE(template_id, version_number));
CREATE TABLE IF NOT EXISTS timeline_template_anchors (id TEXT PRIMARY KEY, template_version_id TEXT NOT NULL REFERENCES timeline_template_versions(id) ON DELETE CASCADE, anchor_key TEXT NOT NULL, default_offset_days INTEGER NOT NULL DEFAULT 0, source TEXT NOT NULL DEFAULT 'manual' CHECK (source IN ('event_start','event_end','manual','derived')), UNIQUE(template_version_id, anchor_key));
CREATE TABLE IF NOT EXISTS timeline_template_items (id TEXT PRIMARY KEY, template_version_id TEXT NOT NULL REFERENCES timeline_template_versions(id) ON DELETE CASCADE, item_key TEXT NOT NULL, type TEXT NOT NULL DEFAULT 'task', title TEXT NOT NULL, priority TEXT NOT NULL DEFAULT 'normal', schedule_mode TEXT NOT NULL DEFAULT 'relative' CHECK (schedule_mode IN ('relative','fixed')), anchor_key TEXT, offset_days INTEGER, due_at TEXT, evidence_required INTEGER NOT NULL DEFAULT 0, dependency_keys_json TEXT, UNIQUE(template_version_id, item_key));
CREATE TABLE IF NOT EXISTS event_plans (id TEXT PRIMARY KEY, event_instance_id TEXT NOT NULL UNIQUE REFERENCES event_instances(id) ON DELETE CASCADE, template_version_id TEXT REFERENCES timeline_template_versions(id) ON DELETE SET NULL, created_at TEXT NOT NULL, created_by_user_id TEXT REFERENCES users(id) ON DELETE SET NULL);
CREATE TABLE IF NOT EXISTS event_plan_anchors (id TEXT PRIMARY KEY, event_plan_id TEXT NOT NULL REFERENCES event_plans(id) ON DELETE CASCADE, anchor_key TEXT NOT NULL, occurs_at TEXT, source TEXT NOT NULL CHECK (source IN ('event_start','event_end','manual','derived')), updated_by_user_id TEXT REFERENCES users(id) ON DELETE SET NULL, updated_at TEXT NOT NULL, UNIQUE(event_plan_id, anchor_key));
CREATE TABLE IF NOT EXISTS event_plan_anchor_events (id TEXT PRIMARY KEY, event_plan_id TEXT NOT NULL REFERENCES event_plans(id) ON DELETE CASCADE, anchor_key TEXT NOT NULL, event_type TEXT NOT NULL, actor_user_id TEXT REFERENCES users(id) ON DELETE SET NULL, data_json TEXT, occurred_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS event_plan_items (id TEXT PRIMARY KEY, event_plan_id TEXT NOT NULL REFERENCES event_plans(id) ON DELETE CASCADE, template_item_id TEXT REFERENCES timeline_template_items(id) ON DELETE SET NULL, type TEXT NOT NULL DEFAULT 'task', title TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open','blocked','completed')), priority TEXT NOT NULL DEFAULT 'normal', anchor_key TEXT, offset_days INTEGER, schedule_mode TEXT NOT NULL DEFAULT 'relative' CHECK (schedule_mode IN ('relative','fixed')), due_at TEXT, manual_override_at TEXT, manual_override_by_user_id TEXT REFERENCES users(id) ON DELETE SET NULL, related_domain TEXT, related_id TEXT, completed_at TEXT, completed_by_user_id TEXT REFERENCES users(id) ON DELETE SET NULL, evidence_required INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS event_plan_assignments (id TEXT PRIMARY KEY, event_plan_item_id TEXT NOT NULL REFERENCES event_plan_items(id) ON DELETE CASCADE, assignee_type TEXT NOT NULL CHECK (assignee_type IN ('user','team','role')), assignee_id TEXT NOT NULL, accepted_at TEXT, ended_at TEXT, assigned_by_user_id TEXT REFERENCES users(id) ON DELETE SET NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS event_plan_item_events (id TEXT PRIMARY KEY, event_plan_item_id TEXT NOT NULL REFERENCES event_plan_items(id) ON DELETE CASCADE, event_type TEXT NOT NULL, actor_user_id TEXT REFERENCES users(id) ON DELETE SET NULL, data_json TEXT, occurred_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS event_plan_item_evidence (id TEXT PRIMARY KEY, event_plan_item_id TEXT NOT NULL REFERENCES event_plan_items(id) ON DELETE CASCADE, label TEXT NOT NULL, url TEXT, attached_by_user_id TEXT REFERENCES users(id) ON DELETE SET NULL, attached_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS event_plan_dependencies (id TEXT PRIMARY KEY, event_plan_item_id TEXT NOT NULL REFERENCES event_plan_items(id) ON DELETE CASCADE, depends_on_item_id TEXT NOT NULL REFERENCES event_plan_items(id) ON DELETE CASCADE, created_by_user_id TEXT REFERENCES users(id) ON DELETE SET NULL, created_at TEXT NOT NULL, UNIQUE(event_plan_item_id, depends_on_item_id), CHECK (event_plan_item_id != depends_on_item_id));
CREATE INDEX IF NOT EXISTS idx_event_plan_items_plan_due ON event_plan_items(event_plan_id, due_at);
CREATE INDEX IF NOT EXISTS idx_event_plan_item_events_item_time ON event_plan_item_events(event_plan_item_id, occurred_at DESC);
